### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by lnmdi** [lnmdi/hello-world#2]
Trying out issues

# Allgemein
|||
|-|-|
|**Kategorie:** FATAL | **Version:** 110.0.18 GA|
|**Zeit:** 22.04.2015 - 11:44:48 | **IP:** 912.168.140.44 local|
|**ProcessID:** 1429682766941 | **Thread:** org.eclipse.jetty.io.AbstractConnection$2@307fd815|
# Message
java.lang.NullPointerException: null
# Stacktrace
at com.lucanet.sarah.server.web.LucaNetClientJettyServlet.logException(LucaNetClientJettyServlet.java:138)
at com.lucanet.sarah.server.web.LucaNetClientJettyServlet.calculateResponse(LucaNetClientJettyServlet.java:94)
at com.lucanet.sarah.server.web.LucaNetClientJettyServlet.doExecuteRequest(LucaNetClientJettyServlet.java:59)
at com.lucanet.sarah.server.web.LucaNetClientJettyServlet.doExecuteRequest(LucaNetClientJettyServlet.java:37) 
# Exception
java.lang.NullPointerException
            at java.lang.reflect.Method.invoke(Unknown Source)

**Comment by lnmdi** [comment]
Mit Screenshot
![splash](https://cloud.githubusercontent.com/assets/23703435/20606256/04793ae2-b270-11e6-90e9-fec00e5a23ba.png)

**Comment by lnmdi** [comment]
Mit Datei
[test.txt](https://github.com/lnmdi/hello-world/files/624692/test.txt)
